[build]
  # Directory with the static HTML site
  base = "/"
  publish = "/"
  command = "echo 'No build required for static HTML site'"

[dev]
  # Static site development
  command = "echo 'No dev command needed for static HTML site'"
  port = 8888
  framework = "#static"

# For the static demo site, we don't need API redirects since we're using mock data
# If you connect to a real backend later, uncomment and update this section
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.com/api/:splat"
#   status = 200
#   force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
